version: '3.1'
services:
  app:
    container_name: app-springboot-example
    image: app-springboot-example
    build: ./
    ports:
      - "8080:8080"
    environment:
      - spring_datasource_url=jdbc:postgresql://dbpostgresql:5432/mydb
      - spring_datasource_username=postgres
      - spring_datasource_password=password
      - spring_datasource_driver-class-name=org.postgresql.Driver
      - spring_jpa_generate-ddl=true
      - spring_jpa_hibernate_ddl-auto=update
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb